# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenDen', '0005_auto_20200111_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='student_associated',
            field=models.ManyToManyField(blank=True, to='lenDen.Students'),
        ),
    ]
