# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenDen', '0006_teachers_student_associated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
